In [19]:
import cv2
import numpy

In [8]:
im_g = cv2.imread("smallgray.png", 0)

In [9]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [10]:
cv2.imwrite("new_smal_gray.png", im_g)

True

In [13]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [14]:
im_g.shape

(3, 5)

In [16]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [17]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [25]:
vms = numpy.vstack((im_g, im_g))

In [28]:
ims = numpy.hstack((vms,vms,vms))

In [29]:
cv2.imwrite("quad_new_smal_gray.png", ims)

True

In [33]:
print(ims)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]
 [187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [34]:
lst=numpy.hsplit(ims,5)

In [38]:
lst[1]

array([[121, 143, 187],
       [255, 147, 198],
       [ 97, 182, 209],
       [121, 143, 187],
       [255, 147, 198],
       [ 97, 182, 209]], dtype=uint8)